import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import ThemeLayout from "@/components/layouts/theme-layouts";
import { Toaster } from "@/components/ui/sonner";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        <ThemeLayout>
          {children}
          <Toaster />
        </ThemeLayout>
      </body>
    </html>
  );
}
